### Site Settings ###
title               : Vo Van Tu

description         : >-
                      Deep Learning Engineer <a target='_blank' rel='noopener noreferrer' href='https://inhandplus.com/'>@InhandPlus</a>.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : tuvovan/tuvovan.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU@v2.2.2


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Vo Van Tu
  image             : https://tuvovan.github.io/assets/img/portfolio_picture.jpg
# behance           : your_username
# dribbble          : your_username
  email             : vovantu.hust@gmail.com
# facebook          : your_username
  github            : tuvovan
# gitlab            : your_username
# instagram         : your_username
  kaggle            : tuvovan211
  linkedin          : tuvv
# medium            : your_username
# soundcloud        : lexorehead
# spotify           : your_username
# stackoverflow     : 7614810
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : MoreheadAlex
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus: your-short-name-disqus                          # Your website Shortname on disqus


### Built-In Google Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: UA-172070520-1

# Custom Google Analytics (Enabled)
google_analytics: UA-172070520-1

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
